"""One-time integration of collection labels and the original official errata."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def replace(path,old,new):
    p=ROOT/path;s=p.read_text(encoding='utf8');assert old in s,(path,old);p.write_text(s.replace(old,new),encoding='utf8')

replace('scripts/import_library.py','CACHE,EDITION,paper_key,edition_of','CACHE,EDITION,paper_key,edition_of,config\nfrom source_info import source_name,paper_name')
replace('scripts/import_library.py','READERS={}','READERS={}\nCORRECTIONS=json.loads((ROOT/"data/answer_corrections32.json").read_text(encoding="utf8"))["corrections"] if EDITION==32 else {}')
replace('scripts/import_library.py','def spans(k,paper,number,heading=False):','def spans(k,paper,number,heading=False):\n    correction=CORRECTIONS.get(f"{paper}-{number}")\n    if k=="a" and correction:return correction["effectiveRanges"]')
replace('scripts/import_library.py',"len(INDEX[k]['pages'])+1", "(config.get('aContentPages',len(INDEX[k]['pages'])) if k=='a' else len(INDEX[k]['pages']))+1")
replace('scripts/import_library.py',"alt=f'第{EDITION}届模拟试题{paper} 第{number}题 {label}原图'","alt=f'{source_name(EDITION,paper)} 第{number}题 {label}原图'")
replace('scripts/import_library.py',"'answerPages':pages(ar),'pdfReady':True", "'answerPages':pages(CORRECTIONS.get(f'{paper}-{number}',{}).get('originalRanges',ar)),'pdfReady':True,'sourcePaperLabel':paper_name(EDITION,paper),'series':config.get('series','annual')")
replace('scripts/import_library.py',"        records.append({'number':number", "        correction=CORRECTIONS.get(f'{paper}-{number}')\n        if correction:items[-1]['answerCorrectionPages']='、'.join(map(str,correction['errataPages']))\n        records.append({'number':number")
replace('scripts/build_numbered_pdfs.py','from fast_pdf import page_count,stamp_template,merge_parts','from fast_pdf import page_count,stamp_template,merge_parts\nfrom source_info import source_name,question_source,score_text')
replace('scripts/build_numbered_pdfs.py',"f'第{EDITION}届模拟试题{paper} · 专题连续编号'","source_name(EDITION,paper,compact=True)+' · 专题连续编号'")
replace('scripts/build_numbered_pdfs.py','{title}（{q["points"]} 分{percent}）','{title}{score_text(q)}')
replace('scripts/build_numbered_pdfs.py',"f'来源：第{EDITION}届 · 模拟试题{q[\"paper\"]} · 原第{q[\"number\"]}题'",'question_source(q)')
replace('scripts/build_numbered_pdfs.py',"['id','title','titleHtml','points','percent']","['id','title','titleHtml','points','percent','sourcePaperLabel','series','answerCorrectionPages']")
replace('scripts/fast_pdf.py',"            title=f'第{entry[\"number\"]}题 · 第{entry[\"sourceEdition\"]}届模拟试题{entry[\"sourcePaper\"]}原第{entry[\"sourceNumber\"]}题'", "            from source_info import source_name\n            title=f'第{entry[\"number\"]}题 · {source_name(entry[\"sourceEdition\"],entry[\"sourcePaper\"],compact=True)}原第{entry[\"sourceNumber\"]}题'")
replace('scripts/rebuild_numbering.py',"'pdf_form_cache.py']","'pdf_form_cache.py','source_info.py']")
replace('scripts/publish_library.py',"scope='、'.join(f'第{e}届{n}套' for e,n in counts.items())","scope='、'.join(f'第{e}届{n}份' if e else f'Chemy联赛{n}届' for e,n in counts.items())")
replace('scripts/publish_library.py','{scope}模拟试题，共','{scope}试题，共')
replace('scripts/publish_library.py',"message or f'Import Chemy {EDITION} mock paper {paper} with cumulative topic PDFs'","message or (f'Import Chemy league edition {paper} with cumulative topic PDFs' if EDITION==0 else f'Import Chemy {EDITION} collection {paper} with cumulative topic PDFs')")
replace('scripts/audit_library.py',"sources=read(ROOT/'sources/manifest.json')['editions'][str(e)]['originalFiles']","entry=read(ROOT/'sources/manifest.json')['editions'][str(e)]\n        sources=entry['originalFiles']+entry.get('workingFiles',[])\n        config=read(ROOT/'data/editions.json')[str(e)]")
replace('scripts/audit_library.py',"if source['kind'] in ['q','a']:","if source['kind'] in ['q','a'] and source['filename']==config[source['kind']]:")
replace('dist/app.js','return q.edition||39;','return q.edition??39;')
replace('dist/app.js',"function paperLabel(key){const parts=String(key).split('-');return parts.length===1?`第39届 · 模拟试题 ${key}`:`第${parts[0]}届 · 模拟试题 ${parts[1]}`;}","function paperLabel(key){const q=questions.find(q=>paperKey(q)===String(key));if(!q)return '';return editionOf(q)===0?`第${q.paper}届 Chemy联赛`:`第${editionOf(q)}届 · ${q.sourcePaperLabel||'模拟试题 '+q.paper}`;}\nfunction scoreText(q){return q.points==null?'':`（${q.points} 分${q.percent==null?'':'，占 '+q.percent+'%'}）`;}")
replace('dist/app.js','套模拟试题','套试卷')
replace('dist/app.js','<span>${q.points} 分</span>',"${q.points==null?'':`<span>${q.points} 分</span>`}")
replace('dist/app.js',"（${q.points} 分${q.percent==null?'':'，占 '+q.percent+'%'}）</h2>","${scoreText(q)}</h2>")
replace('dist/app.js','第 ${editionOf(q)} 届 · 模拟试题 ${q.paper}', '${paperLabel(paperKey(q))}')
replace('dist/app.js','答案合集第 ${q.answerPages} 页</div>',"答案合集第 ${q.answerPages} 页${q.answerCorrectionPages?' · 官方答案补正第 '+q.answerCorrectionPages+' 页':''}</div>")
replace('dist/app.js','.map(e=>`第 ${e} 届`)','.map(e=>e===0?\'Chemy联赛\':`第 ${e} 届`)')
replace('dist/app.js','Chemy · 模拟题','Chemy · 题库')
replace('dist/index.html','第35、36、37、38、39届模拟试题合集','第32～39届试题合集与Chemy联赛')
print('Source names, unscored practice questions and official answer corrections integrated',flush=True)
